package com.space_141105.mortagage;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Application implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Years of amortization")
	private java.lang.Integer amortiation;
	@org.kie.api.definition.type.Label("Applicant")
	private com.space_141105.mortagage.Applicant applicant;
	@org.kie.api.definition.type.Label("Down Payment")
	private java.lang.Integer downpayment;
	@org.kie.api.definition.type.Label("Error details")
	private ValidationErrorDO errors;
	@org.kie.api.definition.type.Label("Mortgage amount")
	private java.lang.Integer mortgageamount;
	@org.kie.api.definition.type.Label("Property")
	private com.space_141105.mortagage.Property property;

	public Application() {
	}

	public java.lang.Integer getAmortiation() {
		return this.amortiation;
	}

	public void setAmortiation(java.lang.Integer amortiation) {
		this.amortiation = amortiation;
	}

	public com.space_141105.mortagage.Applicant getApplicant() {
		return this.applicant;
	}

	public void setApplicant(com.space_141105.mortagage.Applicant applicant) {
		this.applicant = applicant;
	}

	public java.lang.Integer getDownpayment() {
		return this.downpayment;
	}

	public void setDownpayment(java.lang.Integer downpayment) {
		this.downpayment = downpayment;
	}

	public java.lang.Integer getMortgageamount() {
		return this.mortgageamount;
	}

	public void setMortgageamount(java.lang.Integer mortgageamount) {
		this.mortgageamount = mortgageamount;
	}

	public com.space_141105.mortagage.Property getProperty() {
		return this.property;
	}

	public void setProperty(com.space_141105.mortagage.Property property) {
		this.property = property;
	}

	public com.space_141105.mortagage.ValidationErrorDO getErrors() {
		return this.errors;
	}

	public void setErrors(com.space_141105.mortagage.ValidationErrorDO errors) {
		this.errors = errors;
	}

	public Application(java.lang.Integer amortiation,
			com.space_141105.mortagage.Applicant applicant,
			java.lang.Integer downpayment,
			com.space_141105.mortagage.ValidationErrorDO errors,
			java.lang.Integer mortgageamount,
			com.space_141105.mortagage.Property property) {
		this.amortiation = amortiation;
		this.applicant = applicant;
		this.downpayment = downpayment;
		this.errors = errors;
		this.mortgageamount = mortgageamount;
		this.property = property;
	}

}