package com.space_141105.mortagage;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Applicant implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Address")
	private java.lang.String address;
	@org.kie.api.definition.type.Label(value = "Annual Income")
	private java.lang.Integer annualincome;
	@org.kie.api.definition.type.Label(value = "Credit Rating")
	private java.lang.Integer creditrating;
	@org.kie.api.definition.type.Label(value = "Name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label(value = "SSN")
	private java.lang.String ssn;

	public Applicant() {
	}

	public java.lang.String getAddress() {
		return this.address;
	}

	public void setAddress(java.lang.String address) {
		this.address = address;
	}

	public java.lang.Integer getAnnualincome() {
		return this.annualincome;
	}

	public void setAnnualincome(java.lang.Integer annualincome) {
		this.annualincome = annualincome;
	}

	public java.lang.Integer getCreditrating() {
		return this.creditrating;
	}

	public void setCreditrating(java.lang.Integer creditrating) {
		this.creditrating = creditrating;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getSsn() {
		return this.ssn;
	}

	public void setSsn(java.lang.String ssn) {
		this.ssn = ssn;
	}

	public Applicant(java.lang.String address, java.lang.Integer annualincome,
			java.lang.Integer creditrating, java.lang.String name,
			java.lang.String ssn) {
		this.address = address;
		this.annualincome = annualincome;
		this.creditrating = creditrating;
		this.name = name;
		this.ssn = ssn;
	}

}